#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: $0 <create|drop|recreate>" 1>&2
    exit 1
fi

if [ "x$OS" = "xDarwin" ]; then
    export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin
else
    # Make sure we're running as user postgres on Linux
    if [ "x$userid" = "x" ]; then
        echo "\$userid variable not set - quitting" 1>&2
        exit 1
    fi
    if [ "$userid" != "postgres" ]; then
        echo "Not the postgres user, re-executing"
        sudo -u postgres $0 "$@"
        exit 0
    fi
fi

create() {
    #sudo -u postgres psql -d template1 -U postgres -c "CREATE USER ottawagranite_user PASSWORD 'default';"
    createuser --pwprompt ottawagranite_user

    createdb ottawagranite --owner ottawagranite_user
}

drop() {
    dropdb ottawagranite
    dropuser ottawagranite_user
}

case $1 in
    create)
        create
        ;;
    drop)
        drop
        ;;
    recreate)
        drop
        create
        ;;
    *)
        echo "Unsupported option: $1" 1>&2
        exit 1
esac
