#!/bin/sh

id=$(id -u)
userid=$(awk -F: '$3 == '"$id"'{print $1}' /etc/passwd)
echo userid is $userid

if [ "x$OS" = "xDarwin" ]; then
    export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin
else
    # Make sure we're running as user postgres on Linux
    if [ "x$userid" = "x" ]; then
        echo "\$userid variable not set - quitting" 1>&2
        exit 1
    fi
    if [ "$userid" != "postgres" ]; then
        echo "Not the postgres user, re-executing"
        sudo -u postgres $0 "$@"
        exit 0
    fi
fi

create() {
    createuser --pwprompt ottawagranite_user
    createdb ottawagranite --owner ottawagranite_user
}

drop() {
    dropdb ottawagranite
    dropuser ottawagranite_user
}

if [ "x$1" = "x" ]; then
    exec psql -d ottawagranite
fi

case $1 in
    create)
        create
        ;;
    drop)
        drop
        ;;
    recreate)
        drop
        create
        ;;
    *)
        echo "Unsupported option: $1" 1>&2
        exit 1
esac
