# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('hex', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(b'^[0-9a-fA-F]{6}$', b'Not a valid hex code', b'Invalid Code')], verbose_name='hex code')),
            ],
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='finish time')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='finish time')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('format', models.CharField(choices=[(b"Men's Draw", b"Men's Draw"), (b"Men's Fixed", b"Men's Fixed"), (b'Open Draw', b'Open Draw'), (b'Mixed Fixed', b'Mixed Fixed'), (b'Mixed Draw', b'Mixed Draw'), (b'Instructional', b'Instructional'), (b"Women's Fixed", b"Women's Fixed"), (b'Open Fixed', b'Open Fixed'), (b"Women's Draw", b"Women's Draw")], max_length=32, verbose_name='format')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=32, verbose_name='gender')),
                ('jersey', models.CharField(blank=True, max_length=100, verbose_name='jersey')),
            ],
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1, verbose_name='number')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Colour', verbose_name='colour')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Club', verbose_name='club')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[(b'Lead', b'Lead'), (b'Second', b'Second'), (b'Third', b'Third'), (b'Skip', b'Skip'), (b'Alternate', b'Alternate'), (b'Coach', b'Coach'), (b'Undecided', b'Undecided')], max_length=50, verbose_name='position')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitinglist', to='curling.League', verbose_name='league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamplayers', to='curling.Player', verbose_name='player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curling.Team', verbose_name='team')),
            ],
        ),
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='finish time')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.End', verbose_name='end')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Player', verbose_name='player')),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Rock', verbose_name='rock')),
            ],
        ),
        migrations.AddField(
            model_name='rock',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curling.Sheet', verbose_name='sheet'),
        ),
    ]
