# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('currency', models.CharField(choices=[(b'CAD', b'CAD')], max_length=100, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='reference')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('currency', models.CharField(choices=[(b'CAD', b'CAD')], max_length=100, verbose_name='currenct')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('type', models.CharField(choices=[(b'Cash', b'Cash'), (b'Cheque', b'Cheque'), (b'Debit', b'Debit'), (b'Credit', b'Credit'), (b'Money Order', b'Money Order')], max_length=200, verbose_name='type')),
                ('currency', models.CharField(choices=[(b'CAD', b'CAD')], max_length=100, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='reference')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Fee', verbose_name='fee')),
            ],
        ),
    ]
