# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_payments', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payments', to=settings.AUTH_USER_MODEL, verbose_name='staff'),
        ),
        migrations.AddField(
            model_name='fee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_fees', to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
        migrations.AddField(
            model_name='fee',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_fees', to=settings.AUTH_USER_MODEL, verbose_name='staff'),
        ),
        migrations.AddField(
            model_name='fee',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FeeType', verbose_name='type'),
        ),
    ]
