# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('curling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OttawaGraniteLeague',
            fields=[
                ('league_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curling.League')),
                ('rating', models.CharField(blank=True, max_length=20, verbose_name='rating')),
            ],
            bases=('curling.league',),
        ),
        migrations.CreateModel(
            name='OttawaGraniteMember',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('membership_number', models.IntegerField(help_text='An artibrary number assigned to a member for unique identification.', unique=True, verbose_name='membership number')),
                ('latest_membership', models.IntegerField(help_text="FIXME: I don't know what this is for.", verbose_name='latest_membership')),
                ('earliest_membership', models.IntegerField(help_text="FIXME: I don't know what this is for.", verbose_name='earliest membership')),
                ('started_curling', models.IntegerField(help_text="FIXME: I don't know what this is for.", verbose_name='started curling')),
                ('rookie_year', models.IntegerField(help_text='The year you started curling.', verbose_name='rookie year')),
                ('locker_number', models.IntegerField(help_text='Your locker number, if you have one.', verbose_name='locker number')),
                ('parking_stickers', models.IntegerField(help_text='The number of parking stickers you have been issued.', verbose_name='parking stickers')),
                ('social', models.BooleanField(default=False, help_text='This is a social membership, without any actual curling.', verbose_name='social')),
                ('honorary', models.BooleanField(default=False, help_text='An honorary member.', verbose_name='honorary')),
                ('student', models.BooleanField(default=False, help_text='A student membership.', verbose_name='student')),
                ('instructor', models.CharField(blank=True, help_text='Your initial instructor in curling, if any.', max_length=500, verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
            bases=('membership.member',),
        ),
    ]
